using Content.Client.UserInterface.Controls;
using Content.Shared._AS.Exfiltrator; // Replace with Exfiltrator equivalent
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AS.Exfiltrator.UI;

[GenerateTypedNameReferences]
public sealed partial class ExfiltratorBountyRedemptionMenu : FancyWindow
{
    public Action? SellRequested;

    public ExfiltratorBountyRedemptionMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
    }

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }
}
