- type: entity
  parent: [AccessConfigurator, BaseC1Contraband]
  id: AccessConfiguratorCivilian
  name: civilian access configurator
  description: Used to modify the access level requirements for airlocks and other lockable devices. Modified for civilian use.
  components:
    - type: Sprite
      sprite: _AS/Objects/Tools/civilian_access_configurator.rsi
    - type: Clothing
      sprite: _AS/Objects/Tools/civilian_access_configurator.rsi
    - type: AccessOverrider
      accessLevels:
      - Captain
      - Engineering
      - External
      - Frontier # Outpost
      - Janitor
      - Mail
      - Maintenance
      - Medical
      - Mercenary
      - Service
      privilegedIdSlot:
        name: id-card-console-privileged-id
        ejectSound: /Audio/Machines/id_swipe.ogg
        insertSound: /Audio/Weapons/Guns/MagIn/batrifle_magin.ogg
        ejectOnBreak: true
        swap: false
        whitelist:
          components:
          - IdCard
      denialSound:
        path: /Audio/Machines/custom_deny.ogg
      doAfter: 0.5
