- type: entity
  id: SyndiTechFabCircuitboard
  parent: SecurityTechFabCircuitboard
  name: Syndicate techfab machine board
  description: A machine printed circuit board for an SLE techfab.
  components:
    - type: Sprite
      sprite: Objects/Misc/module.rsi
      state: security
    - type: MachineBoard
      prototype: Synditechfab

- type: entity
  id: ThrusterSyndicateMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Syndicate thruster machine board
  components:
  - type: Sprite
    state: security
  - type: MachineBoard
    prototype: ThrusterSyndicate
        requirements:
      Capacitor: 3
    stackRequirements:
      Steel: 5
 - type: entity 
  id: ThrusterMedicMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: SLE thruster machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: ThrusterMedic
    requirements:
      Capacitor: 3
    stackRequirements:
      Steel: 5
